services:
  react:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - internal

  websocket-server:
    build: 
      context: .
      dockerfile: ./local/websocket-server/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./websocket-server:/app
      - ./go-shared:/go-shared
      - ./local/data/logs:/logs
    networks:
      - internal
    restart: always
    environment:
    - LOG_LEVEL=${LOG_LEVEL}
    - FILE_INFO_DEBUG_LEVEL=${FILE_INFO_DEBUG_LEVEL}
    - LOG_DIR=/logs
    - CONTAINER_NAME=websocket-server
    - GAME_SERVICE_BASE_URL=http://game

  game:
    build: 
      context: .
      dockerfile: ./local/game/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./game:/app
      - ./go-shared:/go-shared
      - ./local/data/logs:/logs
    networks:
      - internal
    restart: always
    environment:
    - LOG_LEVEL=${LOG_LEVEL}
    - FILE_INFO_DEBUG_LEVEL=${FILE_INFO_DEBUG_LEVEL}
    - LOG_DIR=/logs
    - CONTAINER_NAME=game
    - REDIS_PASSWORD=${VALKEY_API_KEY}
    - REDIS_PORT=8080
    - REDIS_HOST=valkey
    - DB_PRIMARY_HOST=mysql
    - DB_PRIMARY_PORT=3006
    - DB_PRIMARY_NAME=${MYSQL_DATABASE}
    - DB_PRIMARY_USER=${MYSQL_USER}
    - DB_PRIMARY_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80" 
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./local/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal
    restart: always
  valkey:
    image: valkey/valkey:8.1.2-alpine
    environment:
      - VALKEY_HOST=0.0.0.0
      - VALKEY_PORT=8080
      - VALKEY_API_KEY=${VALKEY_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./local/data/valkey:/data 
    networks:
      - internal
    restart: always  

  nginx:
    build: ./local/nginx
    ports:
      - "${APPLICATION_PORT}:80"
    depends_on:
      - react
      - websocket-server
      - phpmyadmin
    networks:
      - internal
      - external

  flyway:
    image: flyway/flyway:11.9-alpine-mongo
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      FLYWAY_USER: root
      FLYWAY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - mysql
    command: flyway migrate
    networks:
      - internal
    

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

