services:
  react:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - internal

  websocket-server:
    build: ./websocket-server
    ports:
      - "8081:8081"
    volumes:
      - ./websocket-server:/app
    networks:
      - internal
    command: go run -ldflags="-s -w" main.go
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80" 
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./local/data/mysql:/var/lib/mysql
    networks:
      - internal
    restart: always

  nginx:
    build: ./local/nginx
    ports:
      - "80:80"
    depends_on:
      - react
      - websocket-server
      - phpmyadmin
    networks:
      - internal
      - external

  flyway:
    image: flyway/flyway:11.9-alpine-mongo
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      FLYWAY_USER: root
      FLYWAY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - mysql
    command: flyway migrate
    networks:
      - internal
    

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

