services:
  frontend:
    image: ${PREFIX}-frontend${POSTFIX}:${TAG}
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./cloud/data/nginx-frontend:/var/log/nginx

  websocket-server:
    image: ${PREFIX}-websocket-server${POSTFIX}:${TAG}
    volumes:
      - ./cloud/data/logs:/logs
    networks:
      - internal
    depends_on:
      - game
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      FILE_INFO_DEBUG_LEVEL: ${FILE_INFO_DEBUG_LEVEL}
      LOG_DIR: /logs
      CONTAINER_NAME: websocket-server
      GAME_SERVICE_BASE_URL: http://game:8082
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379
      REDIS_HOST: valkey
      GAME_STATUS_CACHE_TIMEOUT: 1
      STAY_CONNECTED_PLAYER: 60
      LOKI_URL: "http://loki:3100"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  game:
    image: ${PREFIX}-game${POSTFIX}:${TAG}
    volumes:
      - ./cloud/data/logs:/logs
    networks:
      - internal
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      FILE_INFO_DEBUG_LEVEL: ${FILE_INFO_DEBUG_LEVEL}
      LOG_DIR: /logs
      CONTAINER_NAME: game
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379
      REDIS_HOST: valkey
      DB_PRIMARY_HOST: mysql
      DB_PRIMARY_PORT: 3306
      DB_PRIMARY_NAME: ${MYSQL_DATABASE}
      DB_PRIMARY_USER: root
      DB_PRIMARY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LOKI_URL: "http://loki:3100"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-server:
    image: ${PREFIX}-api-server${POSTFIX}:${TAG}
    volumes:
      - ./cloud/data/logs:/logs
    networks:
      - internal
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      FILE_INFO_DEBUG_LEVEL: ${FILE_INFO_DEBUG_LEVEL}
      LOG_DIR: /logs
      CONTAINER_NAME: api-server
      GAME_SERVICE_BASE_URL: http://game:8082
      LOKI_URL: "http://loki:3100"
    depends_on:
      - game
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin:5.2.2-fpm-alpine
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./cloud/data/mysql:/var/lib/mysql
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  valkey:
    image: valkey/valkey:8.1.2-alpine
    environment:
      VALKEY_HOST: 0.0.0.0
      VALKEY_PORT: 6379
    volumes:
      - ./cloud/data/valkey:/data 
    networks:
      - internal  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: ${PREFIX}-nginx${POSTFIX}:${TAG}
    ports:
      - target: 80
        published: ${APPLICATION_PORT}
        mode: host
    depends_on:
      - react
      - websocket-server
      - api-server
    networks:
      - internal
      - external
    environment:
      - BASIC_USERNAME=${HTTP_ADMIN_USERNAME}
      - BASIC_PASSWORD=${HTTP_ADMIN_PASSWORD}
    volumes:
      - ./cloud/data/nginx:/var/log/nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  flyway:
    image: flyway/flyway:11.9-alpine-mongo
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      FLYWAY_USER: root
      FLYWAY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - mysql
    command: ["migrate"]
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  redisinsight:
    image: redislabs/redisinsight:2.70
    depends_on:
      - valkey
    networks:
      - internal
    environment:
      - RI_PROXY_PATH=/admin/redis/
      - RI_REDIS_HOST=valkey
    volumes:
      - ./cloud/data/redisinsight:/db
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  grafana:
    image: ${PREFIX}-grafana${POSTFIX}:${TAG}
    depends_on:
      - loki
    networks:
      - internal
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=/admin/grafana/
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  loki:
    image: ${PREFIX}-loki${POSTFIX}:${TAG}
    networks:
      - internal
    volumes:
      - loki:/loki/data

networks:
  internal:
    driver: overlay
    internal: true
  external:
    driver: overlay

volumes:
  grafana:
    driver: local
  loki:
    driver: local